mq: &default_mq
  :adapter: StompAdapter
#  :host: localhost
  :host: 192.168.53.134
  :port: 61613
  :reconnect_delay: 5

:announce:
  :adapter: SpreadAdapter
  :channel: 4803@localhost
  :group:   announce

:scheduler:
  <<: *default_mq
  :name: /queue/development.scheduler
  :reliable: true

:change_events:
  <<: *default_mq
  :name: /topic/change_events
  :reliable: true

:input:
  <<: *default_mq
  :name: /queue/shared
  :reliable: true

:output:
  <<: *default_mq
  :name: /queue/shared
  :reliable: true

:irc_input:
  :adapter: IRCAdapter
  :server: irc.freenode.net
  :port: 6667
  :channel: '#smqueue'
  :nick: smqueue_input

:irc_output:
  :adapter: IRCAdapter
  :server: irc.freenode.net
  :port: 6667
  :channel: '#smqueue'
  :nick: smqueue_output

:readline:
  :adapter: ReadlineAdapter

:stdio:
  :adapter: StdioAdapter

:error:
  :adapter: NullAdapter
